server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ldq?serverTimezone=UTC
    username: root
    password: 4444
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true

